#!/bin/bash

echo -n "sisesta vahemiku algus: "
read algus
echo -n "sisesta vahemiku lopp: "
read lopp

	for (( nr=$algus; nr<=$lopp; nr++ ))
do
	touch fail$nr

	failinimi=fail$nr
	if [ $failinimi ]; then
	echo "$failinimi fail juba olemas"
	echo -n "kas soovid asendada uue failiga? y/n"
	read vastus
	if [ "$vastus" = "y" -o "$vastus" = "Y" ]; then
		rm $failinimi
		touch $failinimi
		fi
	else
	touch $failinimi
	echo "$failinimi on loodud"
	fi
done
