#!/bin/bash
#
# aja järgi teavitamine
#
echo -e "Sisesta aja väärtus : \c"
read aeg
#kontrollime
if   [ $aeg -ge 6 -a $aeg -lt 12 ]; then
		echo "Tere Hommikust"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
		echo "Tere Päevast"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]; then
		echo "Head ood"
else
		echo "Vale seisund"
fi
#skripti lõpp
