#!/bin/bash
#nimi:Kert Kalda
#skriptinimi:menu
#Skripti kirjeldus:skript väljastad söögi kirjelduse vastavalt valikule
#
echo "menüü:
1) steak and potatoes
2) fish and chips
3) soup and salad"
echo -n "Plese make a selection (1 or 2 or 3)"
read valiku_nr
		if [ $valiku_nr -eq 1 ];then
	echo "Stick to yuor ribs.
Watch your cholesterol.
Enjoy your meal!"
	else
		if [ $valiku_nr -eq 2];then
	echo "British are coming!
Enjoy your meal!"
	else
		if [ $valiku_nr -eq 3 ];then
	echo "Health foods...
Dieting is so borring.
Enjoy your meal!"
	fi
	fi
	fi

