#!/bin/bash
#nimi: Kert Kalda
#Skripti nimi: roopkylik
#Skripti kirjeldus: teeb roopkyliku vastavalt rea arvudele
#
echo -n "Sisesta ridade arv: "
read rida
#
for ((r=1; r<$rida+1; r++))
do
echo -n "$r "
#
for (( v=1; v<$(($rida+1-$r+1)); v++))
	do
		echo -n " "
done
#
for (( i = $rida; i <= $rida; i++ ))
do
	for (( j = 1; j <= i ; j++ ))
	do
		echo -n "*"
	done
done
echo ""
done
