#!/bin/bash
#
# muutujate kasutamise näide
#
# defineerime muutuja ja omistame väärtus
# väärtus saadakse whoami käsust
kasutaja=`whoami`
# väljastan muutuja väärtus koos seletusega
echo "Tere!, $kasutaja"
# loome ja väljastamine kell
kell=`date +'%H:%M'`
echo "Kell on $kell"
