#!/bin/bash
#
# arvu positiivsuse/negatiivsuse
#
# kontrollime, kas kasutja sisestas käsurea kaudu 1 parameetri
# kui mitte - trükime kasutusjuhend välja
if [ $# -ne 1 ]; then
	echo "Kasutusjuhend"
	echo "$0 number"
	echo "näiteks: $0 5"
arv=$1
# kontrollime, kas arv on positiivne
# sel juhul arv peab olema suurem kui 0
if [ $arv -gt 0 ]
	echo "$arv on positiivne"
# muidu kui väärtus in negatiivne
# siis arv peab olema väiksem kui 0
elif [ $arv -lt 0 ]; then 
	echo "$arv on negatiivne"
# kui simine tingimus
# või teine tingimus ei sobinud
# siis kasuta else osa
else
	echo "$arv on neutraalne"
# if lause tuleb korralikult lõpetada
fi
# väline if lause tuleb ka korralikult lõpetada
if
