#!/bin/bash
#
# arvu positiivsuse/negatiivsuse
#
# küsime väärtused kasutja käest
echo -n "Sisesta arv: "
read arv
# kontrollime, kas arv on positiivne
# sel juhul arv peab olema suurem kui 0
if [ $arv -gt 0 ]
	echo "$arv on positiivne"
# muidu kui väärtus in negatiivne
# siis arv peab olema väiksem kui 0
elif [ $arv -lt 0 ]; then 
	echo "$arv on negatiivne"
# kui simine tingimus
# või teine tingimus ei sobinud
# siis kasuta else osa
else
	echo "$arv on neutraalne"
# if lause tuleb korralikult lõpetada
fi
